// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  all_profiles_links: dynamic(() => import("./AllProfilesLinks")),
  biography_data: dynamic(() => import("./BiographyData")),
  button_slice: dynamic(() => import("./ButtonSlice")),
  buttons_group: dynamic(() => import("./ButtonsGroup")),
  content_index: dynamic(() => import("./ContentIndex")),
  creations_block: dynamic(() => import("./CreationsBlock")),
  experience: dynamic(() => import("./Experience")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
